# make_golden.ps1 - stage-1 golden files generated by the original core.ps1 (PowerShell 5.1).
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File tools\make_golden.ps1 -Core <path>\core.ps1 [-SingBox <path>\sing-box.exe]
#
# Reads core.ps1 + tests\fixtures\ (read-only, nothing is written there) and
# writes tests\golden\*.json (UTF-8, no BOM). Side-effect paths of core.ps1
# (log/config/state) are redirected to %TEMP%, and InstallRoot is pinned to the
# relative 'vpn-golden-root' so the cache.db path inside the JSON is identical
# on the PowerShell and the Python side.
param(
    [Parameter(Mandatory = $true)][string]$Core,
    [string]$SingBox = '',
    [string]$Fixtures = '',
    [string]$OutDir = ''
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $Fixtures) { $Fixtures = Join-Path $repoRoot 'tests\fixtures' }
if (-not $OutDir) { $OutDir = Join-Path $repoRoot 'tests\golden' }

# Keep the engine path before dot-sourcing: core.ps1 sets $script:SingBox itself
# (core.ps1:17) and would overwrite the parameter of the same name.
$sbx = $SingBox

. $Core    # dot-source: core.ps1 only defines functions on load, it writes nothing

# Redirect side effects (Write-VpnLog / New-SingBoxConfig) to %TEMP%.
$tmp = Join-Path $env:TEMP 'vpn-golden-tmp'
New-Item -ItemType Directory -Force -Path $tmp | Out-Null
$script:LogFile = Join-Path $tmp 'golden.log'
$script:StateFile = Join-Path $tmp 'state.json'
$script:ConfigFile = Join-Path $tmp 'config.json'
$script:InstallRoot = 'vpn-golden-root'   # relative: identical cache.db path on both sides

if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Force -Path $OutDir | Out-Null }

function Save-Golden([object]$obj, [string]$name) {
    $json = ConvertTo-Json -InputObject $obj -Depth 30
    [IO.File]::WriteAllText((Join-Path $OutDir $name), $json, (New-Object System.Text.UTF8Encoding($false)))
}

function Save-Config([string]$name) {
    Copy-Item -Path $script:ConfigFile -Destination (Join-Path $OutDir $name) -Force
}

# --- 1) Parse-NodeList: plain and base64 subscriptions must give identical nodes
$body = [IO.File]::ReadAllText((Join-Path $Fixtures 'subscription.txt'), [Text.Encoding]::UTF8)
$nodes = Parse-NodeList $body
Save-Golden $nodes 'parse-nodes.json'

$b64body = [IO.File]::ReadAllText((Join-Path $Fixtures 'subscription-b64.txt'), [Text.Encoding]::UTF8)
$nodesB64 = Parse-NodeList $b64body
Save-Golden $nodesB64 'parse-nodes-b64.json'

# --- 2) New-SingBoxConfig scenarios (config.json is rewritten on every call)
# all nodes, tun, extra app + duplicate steam.exe (tests Select-Object -Unique)
$null = New-SingBoxConfig -Nodes $nodes -Mode tun -AppList @('mygame.exe', 'steam.exe')
Save-Config 'config-tun.json'

# proxy mode, only the selected subset -> urltest group + socks/http inbounds
$null = New-SingBoxConfig -Nodes $nodes -Mode proxy -Selected @('node-1', 'node-8', 'node-16') -OnlySelected
Save-Config 'config-proxy-selected.json'

# exactly one selected node -> selector branch
$null = New-SingBoxConfig -Nodes $nodes -Mode tun -Selected @('node-7') -OnlySelected
Save-Config 'config-single.json'

# --- 3) optional: `sing-box check` on every generated config
if ($sbx) {
    foreach ($f in @('config-tun.json', 'config-proxy-selected.json', 'config-single.json')) {
        $p = Start-Process -FilePath $sbx -ArgumentList @('check', '-c', "`"$(Join-Path $OutDir $f)`"") -NoNewWindow -Wait -PassThru
        if ($p.ExitCode -ne 0) { throw "sing-box check FAILED: $f" }
        Write-Host ("sing-box check ok: " + $f)
    }
}

Write-Host ("goldens written to " + $OutDir)
